
train_dataset:
  - name: "invig-q"
    path: "/mnt/bn/hri-lq/datasets/hf/invig"
    task: "question"
    prob: 0.1
  - name: "invig-a"
    path: "/mnt/bn/hri-lq/datasets/hf/invig"
    task: "answer"
    prob: 0.1
  - name: "invig-g"
    path: "/mnt/bn/hri-lq/datasets/hf/invig"
    task: "grounding"
    prob: 0.15
  - name: "guesswhat-q"
    path: "/mnt/bn/hri-lq/datasets/hf/guesswhat"
    task: "question"
    prob: 0.15
  - name: "guesswhat-a"
    path: "/mnt/bn/hri-lq/datasets/hf/guesswhat"
    task: "answer"
    prob: 0.1
  - name: "guesswhat-g"
    path: "/mnt/bn/hri-lq/datasets/hf/guesswhat"
    task: "grounding"
    prob: 0.2
  - name: "visdial-q"
    path: "/mnt/bn/hri-lq/datasets/hf/visdial"
    task: "question"
    prob: 0.1
  - name: "visdial-a"
    path: "/mnt/bn/hri-lq/datasets/hf/visdial"
    task: "answer"
    prob: 0.1

valid_dataset: 
  - name: "guesswhat-g"
    path: "/mnt/bn/hri-lq/datasets/hf/guesswhat"
    task: "grounding"
    prob: 0.2

