
env:
    path_ofa: "/mnt/bn/hri-lq/projects/VLDD/OFA"
    path_invig: "/mnt/bn/hri-lq/projects/VLDD/OFA-Invig"
    path_tokenizer: "/mnt/bn/hri-lq/projects/VLDD/Link/ofa-pretrain/hf/ofa-large"
    path_images:
      coco: "/mnt/bn/hri-lq/datasets/images/coco"
      visdial: "/mnt/bn/hri-lq/datasets/images/visdial"
      openimages_v1.2: "/mnt/bn/hri-lq/datasets/images/openimages_v1.2"
      cc_sbu_align: "/mnt/bn/hri-lq/datasets/images/cc_sbu_align"

train:  # 目标1_000_000
  - name: "invig"  # 17652
    path: /mnt/bn/hri-lq/datasets/hf-cache/invig
    tasks: ["invig_question", "invig_answer", "invig_grounding"]
    probs: [0.02, 0.02, 0.02]
  - name: guesswhat  # 71_165
    path: /mnt/bn/hri-lq/datasets/hf-cache/guesswhat
    tasks: ["guesswhat_question", "guesswhat_answer", "guesswhat_grounding"]
    probs: [0.05, 0.05, 0.05]
  - name: visdial  # 106_061
    path: /mnt/bn/hri-lq/datasets/hf-cache/visdial
    tasks: ["visdial_question", "visdial_answer"]
    probs: [0.05, 0.05]
  - name: refcoco  # 42_404
    path: /mnt/bn/hri-lq/datasets/hf-cache/refcoco
    tasks: ["refcoco_grounding"]
    probs: [0.025]
  - name: refcocog  # 42_404
    path: /mnt/bn/hri-lq/datasets/hf-cache/refcocog
    tasks: ["refcoco_grounding"]
    probs: [0.025]
  - name: refcocoplus  # 42_404
    path: /mnt/bn/hri-lq/datasets/hf-cache/refcocoplus
    tasks: ["refcoco_grounding"]
    probs: [0.025]
  - name: cc_sbu_align  # 3_400
    path: /mnt/bn/hri-lq/datasets/hf-cache/cc_sbu_align
    tasks: ["cc_sbu_align_caption"]
    probs: [0.005]
  - name: "objects365"
    path: "/mnt/bn/data-lq/datasets-hf/vision/objects365"
    tasks: ["objects365_grounding"]
    streaming: true
    probs: [0.05]

validation: 
  - name: "invig"  # 17652
    path: /mnt/bn/hri-lq/datasets/hf-cache/invig
    tasks: ["invig_grounding"]
    probs: [0.5]
  - name: guesswhat  # 71165
    path: /mnt/bn/hri-lq/datasets/hf-cache/guesswhat
    tasks: ["guesswhat_grounding"]
    probs: [0.5]
