
env:
    path_exclude_images: "./attachments/test_images.json"
    path_images:
        coco: "/path/to/images/coco"
        visdial: "/path/to/images/visdial"
        openimages_v1.2: "/path/to/images/openimages_v1.2"
        cc_sbu_align: "/path/to/images/cc_sbu_align"
        cc3m_llava: "/path/to/images/cc3m_llava"

hparam:
    max_src_length: 240
    max_tgt_length: 320

train:  # 1M
  - name: "invig"  # 17k
    path: /path/to/hf-cache/invig
    tasks: ["invig_question", "invig_answer", "invig_grounding"]
    probs: [1, 1, 1]
  - name: guesswhat  # 92k （68k）
    path: /path/to/hf-cache/guesswhat
    tasks: ["guesswhat_question", "guesswhat_answer", "guesswhat_grounding"]
    probs: [1, 1, 1]
  - name: visdial  # 123k (103k)
    path: /path/to/hf-cache/visdial
    tasks: ["visdial_question", "visdial_answer", "visdial_caption"]
    probs: [1, 1, 0.2]
  - name: refcoco  # 42k (31k)
    path: /path/to/hf-cache/refcoco
    tasks: ["refcoco_grounding"]
    probs: [0.3]
  - name: refcocog  # 42k (33k)
    path: /path/to/hf-cache/refcocog
    tasks: ["refcoco_grounding"]
    probs: [0.3]
  - name: refcocoplus  # 42k (31k)
    path: /path/to/hf-cache/refcocoplus
    tasks: ["refcoco_grounding"]
    probs: [0.3]
  - name: cc_sbu_align  # 3k (3k)
    path: /path/to/hf-cache/cc_sbu_align
    tasks: ["cc_sbu_align_caption"]
    probs: [1]
  # - name: "objects365"  # ??
  #   path: "vision/objects365"
  #   tasks: ["objects365_grounding"]
  #   n_samples: 100_000
  #   streaming: true
  #   probs: [0.1]
  - name: "llava_instruct_150k"  # 150k (129k)
    path: "/path/to/hf-cache/llava_instruct_150k"
    tasks: ["llava_instruct_150k"]
    probs: [0.7]
  - name: "llava_conversation_58k"  # 58k (46k)
    path: "/path/to/hf-cache/llava_conversation_58k"
    tasks: ["llava_conversation_58k"]
    probs: [1.0]
  - name: "llava_complex_reasoning_77k"  # 77k (63k)
    path: "/path/to/hf-cache/llava_complex_reasoning_77k"
    tasks: ["llava_complex_reasoning_77k"]
    probs: [0.7]
  - name: "llava_detail_23k"  # 23k (17k)
    path: "/path/to/hf-cache/llava_detail_23k"
    tasks: ["llava_detail_23k"]
    probs: [0.7]
  - name: "openimages"  # 29k
    path: "/path/to/hf-cache/openimages_v1.2"
    tasks: ['openimages_detection']
    probs: [0.5]

validation: 
  - name: "invig"  # 17652
    path: /path/to/hf-cache/invig
    tasks: ["invig_grounding"]
    probs: [0.1]
  - name: guesswhat  # 71165
    path: /path/to/hf-cache/guesswhat
    tasks: ["guesswhat_grounding"]
    probs: [1]

test:
  guesswhat_grounding_end2end: 
    path: /path/to/hf-cache/guesswhat
    task: "guesswhat_grounding"
    style: 0
  guesswhat_grounding: 
    path: /path/to/hf-cache/guesswhat
    task: "guesswhat_grounding"
    style: 0
  guesswhat_oracle: 
    path: /path/to/hf-cache/guesswhat
    task: "guesswhat_answer"
    style: 0
  invig_grounding_end2end: 
    path: /path/to/hf-cache/invig
    task: "invig_grounding"
    style: 0
  invig_grounding: 
    path: /path/to/hf-cache/invig
    task: "invig_grounding"
    style: 0
  invig_oracle: 
    path: /path/to/hf-cache/invig
    task: "invig_answer"
    style: 0
